name: Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd coj-be
            echo ${{ secrets.REMOTE_SSH_PASSWORD }} | sudo -S git pull
            echo ${{ secrets.REMOTE_SSH_PASSWORD }} | sudo -S npm install
            echo ${{ secrets.REMOTE_SSH_PASSWORD }} | sudo -S forever stop 0
            echo ${{ secrets.REMOTE_SSH_PASSWORD }} | sudo -S forever start app.js
